#!/bin/sh

while [ $# -gt 0 ]; do
    arg=$1

    case $arg in
        start)
            docker-compose up --build --force-recreate -d
        ;;
        ubuntu14)
            docker-compose exec ubuntu14 ansible-playbook -i 'localhost,' -c local /etc/ansible/roles/ansible-role-server-base/tests/test.yml
        ;;
        ubuntu16)
            docker-compose exec ubuntu16 ansible-playbook -i 'localhost,' -c local /etc/ansible/roles/ansible-role-server-base/tests/test.yml
        ;;
        stop)
            docker-compose stop
        ;;
    esac
    shift
done