---
- name: configure os
  set_fact:
    server_base_os: "{{ansible_distribution|lower}}{{ansible_distribution_major_version|int}}"

- name: include os variables
  include_vars: "{{server_base_os}}.yml"
  when: server_base_os is defined and server_base_os != ""

# define os variables

- name: define server_base_main_packages
  set_fact:
    server_base_main_packages: "{{__server_base_main_packages}}"
  when: server_base_main_packages is not defined

# setup os

- name: setup {{server_base_os}}
  include: "{{server_base_os}}.yml"
  when: server_base_os is defined and server_base_os != ""