---
- name: update apt cache for upgrade packages
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: server_base_apt_upgrade != ""

################################################################################################

- name: check uname for installing linux image extra
  shell: echo $(uname -r)
  register: server_base_install_linux_image_extra_uname
  when: server_base_install_linux_image_extra == "yes"

- name: install linux image extra
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - "linux-image-extra-{{server_base_install_linux_image_extra_uname.stdout}}"
    - "linux-image-extra-virtual"
  when: server_base_install_linux_image_extra == "yes"

################################################################################################

- name: configure aliases
  template: src={{server_base_os}}/alias.tpl dest=/root/.bash_aliases

################################################################################################

- name: install main packages
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items: "{{server_base_main_packages}}"

- name: install optional packages
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items: "{{server_base_optional_packages}}"

################################################################################################

- name: upgrade packages
  apt:
    upgrade: "{{server_base_apt_upgrade}}"
  when: server_base_apt_upgrade != ""