---
- name: configure aliases
  template: src={{server_base_os}}/alias.tpl dest=/root/.bash_aliases

- name: install main packages
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items: "{{server_base_main_packages}}"

- name: install optional packages
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items: "{{server_base_optional_packages}}"