---
- name: configure aliases
  template: src={{server_base_os}}/alias.tpl dest=/root/.bash_aliases

- name: configure timezone
  template: src={{server_base_os}}/timezone.tpl dest=/etc/timezone
  notify: server_base_update_timezone

- name: generating locales
  locale_gen: name={{item}} state=present
  with_items: "{{server_base_locales}}"

- name: install ntp packages
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items: "{{server_base_ntp_packages}}"
  notify: server_base_command_update_ntp

- name: install main packages
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items: "{{server_base_main_packages}}"