---
- name: update apt cache for upgrade packages
  apt:
    update_cache: yes
    cache_valid_time: 3600
  when: server_base_apt_upgrade != ""

- name: upgrade packages
  apt:
    upgrade: "{{server_base_apt_upgrade}}"
  when: server_base_apt_upgrade != ""

- name: configure aliases
  template: src={{server_base_os}}/alias.tpl dest=/root/.bash_aliases

- name: generating locales
  locale_gen: name={{item}} state=present
  with_items: "{{server_base_locales}}"

- name: install main packages
  apt: pkg={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items: "{{server_base_main_packages}}"